import 'features/high_intensity_interval/domain/entities/exercise.dart';
import 'features/high_intensity_interval/domain/enums/equipment.dart';
import 'features/high_intensity_interval/domain/enums/tag.dart';

final EXERCISES_DATA = [
  Exercise(
    id: 'e1',
    title: 'Standard Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e2',
    title: 'Squat',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e3',
    title: 'Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e4',
    title: 'Jumping Jack',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e5',
    title: 'Pullup',
    tags: [Tag.Pull],
    equipment: Equipment.PullUpBar,
  ),
  Exercise(
    id: 'e6',
    title: 'Sit-up',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e7',
    title: 'Russian Twist',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e8',
    title: 'Pike Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e9',
    title: 'Forward Lunge',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e10',
    title: 'Inverted Row',
    tags: [Tag.Pull],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e11',
    title: 'Wide Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e12',
    title: 'Diamond Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e13',
    title: 'Hindu Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e14',
    title: 'Dive Bomber Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e15',
    title: 'Spider Man Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e16',
    title: 'Plank Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e17',
    title: 'Planche Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e18',
    title: 'Pseudo Planche Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e19',
    title: 'Staggered Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e20',
    title: 'Close Grip Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e21',
    title: 'Reverse Hands Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e22',
    title: 'Clapping Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  //TODO: add Tag.Legs if logic changed
  Exercise(
    id: 'e23',
    title: 'Raised Leg Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e24',
    title: 'Decline Push-up',
    tags: [Tag.Push],
    equipment: Equipment.PlyometricBox,
  ),
  Exercise(
    id: 'e25',
    title: 'Incline Push-up',
    tags: [Tag.Push],
    equipment: Equipment.PlyometricBox,
  ),
  Exercise(
    id: 'e26',
    title: 'Power Push-up',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e27',
    title: 'Hindu Squat',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e28',
    title: 'Side-to-side Lunge',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e29',
    title: 'Calf Raise',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e30',
    title: 'Jump Squat',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e31',
    title: 'Reverse Lunge',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e32',
    title: 'Duck Walk',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e33',
    title: 'Pistol Squat',
    tags: [Tag.Legs],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e34',
    title: 'Box Squat',
    tags: [Tag.Legs],
    equipment: Equipment.PlyometricBox,
  ),
  Exercise(
    id: 'e35',
    title: 'Step Up',
    tags: [Tag.Legs],
    equipment: Equipment.PlyometricBox,
  ),
  Exercise(
    id: 'e36',
    title: 'Single Leg Deadlift',
    tags: [Tag.Legs],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e37',
    title: 'Romanian Deadlift',
    tags: [Tag.Legs],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e38',
    title: 'Forward Weighted Lunge',
    tags: [Tag.Legs],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e39',
    title: 'Reverse Weighted Lunge',
    tags: [Tag.Legs],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e40',
    title: 'Side-to-side Weighted Lunge',
    tags: [Tag.Legs],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e41',
    title: 'Split Squat',
    tags: [Tag.Legs],
    equipment: Equipment.PlyometricBox,
  ),
  Exercise(
    id: 'e42',
    title: 'Front Squat',
    tags: [Tag.Legs],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e43',
    title: 'Straight Arm Plank',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e44',
    title: 'Bridge',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e45',
    title: 'Elbow Plank',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e46',
    title: 'High Knee',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e47',
    title: 'Boat Pose',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e48',
    title: 'V Plank',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e49',
    title: 'Raised Leg Plank',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e50',
    title: 'Side Plank',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e51',
    title: 'Raised Arm Plank',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e52',
    title: 'Mountain Climber',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e53',
    title: 'Scissor Kick',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e54',
    title: 'Bicycle Kick',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e55',
    title: 'Spider Man Plank',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  //might be wrong name
  Exercise(
    id: 'e56',
    title: 'In And Out',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e57',
    title: 'Crunch',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e58',
    title: 'Reverse Crunch',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e59',
    title: 'L Sit',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e60',
    title: 'Star Plank',
    tags: [Tag.Core],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e61',
    title: 'Hollow Rock',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e62',
    title: 'Leg Raise',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e63',
    title: 'Flutter Kick',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e64',
    title: 'Toe Tap',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e65',
    title: 'Windshield Wiper',
    tags: [Tag.Core],
    equipment: Equipment.YogaMat,
  ),
  Exercise(
    id: 'e66',
    title: 'Chin-up',
    tags: [Tag.Pull],
    equipment: Equipment.PullUpBar,
  ),
  Exercise(
    id: 'e67',
    title: 'Row',
    tags: [Tag.Pull],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e68',
    title: 'Shrug',
    tags: [Tag.Pull],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e69',
    title: 'Pull-up',
    tags: [Tag.Pull],
    equipment: Equipment.PullUpBar,
  ),
  Exercise(
    id: 'e70',
    title: 'Deadlift',
    tags: [Tag.Pull],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e71',
    title: 'Hammer Curl',
    tags: [Tag.Pull],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e72',
    title: 'Typewriter Pull-up',
    tags: [Tag.Pull],
    equipment: Equipment.PullUpBar,
  ),
  Exercise(
    id: 'e73',
    title: 'Cactus Hold',
    tags: [Tag.Pull],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e74',
    title: 'Good Morning',
    tags: [Tag.Pull],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e75',
    title: 'Cat Cow',
    tags: [Tag.Pull],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e76',
    title: 'Super Man',
    tags: [Tag.Pull],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e77',
    title: 'Back Rotation',
    tags: [Tag.Pull],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e78',
    title: 'Close Grip Pull-up',
    tags: [Tag.Pull],
    equipment: Equipment.PullUpBar,
  ),
  Exercise(
    id: 'e79',
    title: 'Wide Grip Pull-up',
    tags: [Tag.Pull],
    equipment: Equipment.PullUpBar,
  ),
  Exercise(
    id: 'e80',
    title: 'Preacher Curl',
    tags: [Tag.Pull],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e81',
    title: 'Dumbbell Swing',
    tags: [Tag.Pull],
    equipment: Equipment.Dumbbell,
  ),
  Exercise(
    id: 'e82',
    title: 'Push-up With Rotation',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e83',
    title: 'Shoulder Tap',
    tags: [Tag.Push],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e84',
    title: 'Pull-up Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.PullUpBar,
  ),
  Exercise(
    id: 'e85',
    title: 'Squat Jack',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e86',
    title: 'Low Jack',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e87',
    title: 'Jumping Lunge',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e88',
    title: 'Plyo Jack',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e89',
    title: 'Plyo Inch Worm',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e90',
    title: 'Inch Worm',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e91',
    title: 'Ten Count',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e92',
    title: 'Side-to-side Squat Jump',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e93',
    title: 'Step Back Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e94',
    title: 'Dead Man Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e95',
    title: 'Single Arm Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e96',
    title: 'Spider Man Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e97',
    title: 'T Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e98',
    title: 'Knee Tuck Burpee',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e99',
    title: 'Knee Tuck Jumping Jack',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e100',
    title: 'Sprint',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e101',
    title: 'Butt Kicker',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e102',
    title: 'Vertical Mountain Climber',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e103',
    title: 'Heisman',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  Exercise(
    id: 'e104',
    title: 'Plank Jack',
    tags: [Tag.FullBody],
    equipment: Equipment.None,
  ),
  // Exercise(
  //   id: '',
  //   title: '',
  //   tags: [Tag.],
  //   equipment: Equipment.,
  // ),
];
